### ISSUE TITLE
Could you provide an example of how to use hypercomplex to solve "real world analysis problems"

### ISSUE THREAD

**Issue by dvberkel** [AngryMaciek/hypercomplex#25]
Hi @AngryMaciek 

**Is your feature request related to a problem? Please describe.**
I am missing a "real world" problem and how to solve it with `hypercomplex` in the documentation

**Describe the solution you'd like**
I would like to see a description of a problem that is well suited to solve with hypercomplex numbers, and see example code how to solve it with your software.

**Describe alternatives you've considered**
I have not considered alternatives yet, but I am open to suggestions.

**Additional context**
I am a reviewer for your submission to the Journal of Open Source Software. Right of the bat, I really like your project, the energy you devoted to the project, it's documentation and the state of the repository.

One of the items that I need to review, as per issue [openjournals/joss-reviews#3096](https://github.com/openjournals/joss-reviews/issues/3096), is the example usage. For starters, the available documentation perfectly describes how to use your work. But what I am missing is an "real world" problem being solved with your software.

That is why I opened this issue to see if we can come up with a "real world" problem that demonstrates the power of the software.

**Comment by AngryMaciek** [comment]
Hi @dvberkel,

Thanks for the kind words! Let's consider our options:

I don't think humanity at its current state of knowledge has any **real world** applications to  32>=dim. algebras.
Hopefully my package could contribute to a breakthrough... 😅

As for Sedonions, the only single resource I found was an ML publication from 2020 about their use in a neural network:
https://ieeexplore.ieee.org/document/9160921
This looks really cool and hopefully we might see some real progress in that direction in the future, but I think it's too early for me to implement any examples on my own. Plus, such a program would be rather complex and by itself could serve as another project...

OK, so we try Octonions. I was looking through the wiki and found some references to their applications:
https://en.wikipedia.org/wiki/Octonion#Applications
The problem here is that the applications they describe here are mostly in the field of physics, in which I have no training at all. Maybe if I was a physics PhD I could write some code that would perform meaningful calculations on octonions and provide a short interpretation but unfortunately I lack domain-specific knowledge. Apart from that they also mention robotics and (again) deep learning - but also rather specific tasks, way above my competence level.

Fine, let's focus on Quaternions. Here we can easily find that they represent rotations in 3D:
https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation
I guess that I could implement a simple program that rotates an object in space. But this will still be an abstract proof of principle, not really a real world application.

I designed this small library mostly for these above-mentioned experts who work on Octonions and Sedonions and use them in their domain. I would like to aid all these ML specialists, physicists and robotic engineers solve their problems more efficiently. But I'm not one of them myself... Therefore I would claim that in this specific case it is hard to provide a real-world application. I hope you notice that from the nature of this library. It's not really aimed to solve one well-defined task. Please note that in your checklist it says: _Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)._ So I guess this submission might not be "ideal"...

**Comment by dvberkel** [comment]
Hi @AngryMaciek 

I totally agree with your assessment of the "real world" applications. I searched around myself, and I could not easily find more compelling application then rotations.

I think you did your best effort

**Comment by AngryMaciek** [comment]
Thank you very much for your help and understanding.
